version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: gomod
    directory: "/go/excellent"
    schedule:
      interval: "daily"
