name: Summary

on: workflow_dispatch

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - run: |
          {
            echo "## Summary"
            echo "- Narumi"
            echo "- Sumire"
          } >> "${GITHUB_STEP_SUMMARY}"
