name: Golang Test

on:
  pull_request:
    paths:
      - "go/**/*.go"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: .go-version
      - name: Run tests
        run: |
          {
            echo "## Summary"
            go test -v --cover go/excellent/*.go
          } >> "${GITHUB_STEP_SUMMARY}"
